In [23]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv('../data/2020_2021_nba_season_player_stats.csv')

In [48]:
df = df[~df['Unnamed: 0'].isna()]
df = df.drop(columns=['Unnamed: 0'])
df['game_location'] = df['game_location'].replace(['@', np.nan], ['Away', 'Home'])
df

,player,ranker,game_season,date_game,age,team_id,game_location,opp_id,game_result,gs,...,drb,trb,ast,stl,blk,tov,pf,pts,game_score,plus_minus
0,Solomon Hill,1,1,2020-12-23,29-280,ATL,Away,CHI,W (+20),0,...,3,3,0,0,1,3,2,0,-4.3,-8
1,Solomon Hill,2,2,2020-12-26,29-283,ATL,Away,MEM,W (+10),0,...,1,2,0,0,0,0,2,6,3.5,+3
2,Solomon Hill,3,3,2020-12-28,29-285,ATL,Home,DET,W (+8),0,...,2,2,0,1,1,1,3,12,8.1,+14
3,Solomon Hill,4,4,2020-12-30,29-287,ATL,Away,BRK,L (-4),0,...,1,2,0,0,0,1,3,9,4.8,-9
4,Solomon Hill,5,5,2021-01-01,29-289,ATL,Away,BRK,W (+18),0,...,4,4,1,1,1,0,1,6,3.7,+20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21712,Thomas Bryant,6,6,2021-01-01,23-154,WAS,Away,MIN,W (+21),1,...,5,7,2,0,0,2,1,18,17.4,+25
21713,Thomas Bryant,7,7,2021-01-03,23-156,WAS,Away,BRK,W (+1),1,...,12,14,2,1,0,1,4,21,21.0,-1
21714,Thomas Bryant,8,8,2021-01-06,23-159,WAS,Away,PHI,L (-5),1,...,4,6,1,0,0,0,4,11,10.1,-14
21715,Thomas Bryant,9,9,2021-01-08,23-161,WAS,Away,BOS,L (-9),1,...,6,8,2,1,1,0,2,7,8.4,-12
21716,Thomas Bryant,10,10,2021-01-09,23-162,WAS,Home,MIA,L (-4),1,...,0,0,0,0,0,0,0,0,0.0,-4

In [49]:
list(df.columns)

['player',
 'ranker',
 'game_season',
 'date_game',
 'age',
 'team_id',
 'game_location',
 'opp_id',
 'game_result',
 'gs',
 'mp',
 'fg',
 'fga',
 'fg_pct',
 'fg3',
 'fg3a',
 'fg3_pct',
 'ft',
 'fta',
 'ft_pct',
 'orb',
 'drb',
 'trb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'game_score',
 'plus_minus']

In [50]:
df = df.rename(columns={'team_id': 'team_name', 'opp_id': 'opponent_name', 'gs': 'started_game', 'mp': 'minutes_played', 'fg': 'field_goals_made', 'fga': 'field_goals_attempts', 'fg_pct': 'field_goal_percentage', 'fg3':'field_goals_three_made', 'fg3a': 'field_goals_three_attempts', 'fg3_pct': 'field_goal_three_percentage', 'ft': 'free_throws_made', 'fta': 'free_throw_attempts', 'ft_pct': 'free_throw_percentage', 'orb': 'offensive_rebounds', 'drb':'defensive_rebounds', 'trb': 'total_rebounds', 'ast': 'assists', 'stl': 'steals', 'blk': 'blocks', 'tov': 'turn_overs', 'pf': 'personal_fouls', 'pts': 'points_scored', 'ranker': 'team_season_game', 'game_season': 'player_season_game'})

In [51]:
df['started_game'] = df['started_game'].replace(['0', '1'], ['No', 'Yes'])
df

,player,team_season_game,player_season_game,date_game,age,team_name,game_location,opponent_name,game_result,started_game,...,defensive_rebounds,total_rebounds,assists,steals,blocks,turn_overs,personal_fouls,points_scored,game_score,plus_minus
0,Solomon Hill,1,1,2020-12-23,29-280,ATL,Away,CHI,W (+20),No,...,3,3,0,0,1,3,2,0,-4.3,-8
1,Solomon Hill,2,2,2020-12-26,29-283,ATL,Away,MEM,W (+10),No,...,1,2,0,0,0,0,2,6,3.5,+3
2,Solomon Hill,3,3,2020-12-28,29-285,ATL,Home,DET,W (+8),No,...,2,2,0,1,1,1,3,12,8.1,+14
3,Solomon Hill,4,4,2020-12-30,29-287,ATL,Away,BRK,L (-4),No,...,1,2,0,0,0,1,3,9,4.8,-9
4,Solomon Hill,5,5,2021-01-01,29-289,ATL,Away,BRK,W (+18),No,...,4,4,1,1,1,0,1,6,3.7,+20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21712,Thomas Bryant,6,6,2021-01-01,23-154,WAS,Away,MIN,W (+21),Yes,...,5,7,2,0,0,2,1,18,17.4,+25
21713,Thomas Bryant,7,7,2021-01-03,23-156,WAS,Away,BRK,W (+1),Yes,...,12,14,2,1,0,1,4,21,21.0,-1
21714,Thomas Bryant,8,8,2021-01-06,23-159,WAS,Away,PHI,L (-5),Yes,...,4,6,1,0,0,0,4,11,10.1,-14
21715,Thomas Bryant,9,9,2021-01-08,23-161,WAS,Away,BOS,L (-9),Yes,...,6,8,2,1,1,0,2,7,8.4,-12
21716,Thomas Bryant,10,10,2021-01-09,23-162,WAS,Home,MIA,L (-4),Yes,...,0,0,0,0,0,0,0,0,0.0,-4

In [52]:
#df[df.isna().any(axis=1)]
df.isna().any()

player                         False
team_season_game               False
player_season_game              True
date_game                      False
age                            False
team_name                      False
game_location                  False
opponent_name                  False
game_result                    False
started_game                   False
minutes_played                  True
field_goals_made                True
field_goals_attempts            True
field_goal_percentage           True
field_goals_three_made          True
field_goals_three_attempts      True
field_goal_three_percentage     True
free_throws_made                True
free_throw_attempts             True
free_throw_percentage           True
offensive_rebounds              True
defensive_rebounds              True
total_rebounds                  True
assists                         True
steals                          True
blocks                          True
turn_overs                      True
personal_fouls                  True
points_scored                   True
game_score                      True
plus_minus                      True
dtype: bool

In [53]:
df['field_goal_percentage'] = df['field_goal_percentage'].replace([np.nan], [-1])
df['field_goal_three_percentage'] = df['field_goal_three_percentage'].replace([np.nan], [-1])
df['free_throw_percentage'] = df['free_throw_percentage'].replace([np.nan], [-1])
df

,player,team_season_game,player_season_game,date_game,age,team_name,game_location,opponent_name,game_result,started_game,...,defensive_rebounds,total_rebounds,assists,steals,blocks,turn_overs,personal_fouls,points_scored,game_score,plus_minus
0,Solomon Hill,1,1,2020-12-23,29-280,ATL,Away,CHI,W (+20),No,...,3,3,0,0,1,3,2,0,-4.3,-8
1,Solomon Hill,2,2,2020-12-26,29-283,ATL,Away,MEM,W (+10),No,...,1,2,0,0,0,0,2,6,3.5,+3
2,Solomon Hill,3,3,2020-12-28,29-285,ATL,Home,DET,W (+8),No,...,2,2,0,1,1,1,3,12,8.1,+14
3,Solomon Hill,4,4,2020-12-30,29-287,ATL,Away,BRK,L (-4),No,...,1,2,0,0,0,1,3,9,4.8,-9
4,Solomon Hill,5,5,2021-01-01,29-289,ATL,Away,BRK,W (+18),No,...,4,4,1,1,1,0,1,6,3.7,+20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21712,Thomas Bryant,6,6,2021-01-01,23-154,WAS,Away,MIN,W (+21),Yes,...,5,7,2,0,0,2,1,18,17.4,+25
21713,Thomas Bryant,7,7,2021-01-03,23-156,WAS,Away,BRK,W (+1),Yes,...,12,14,2,1,0,1,4,21,21.0,-1
21714,Thomas Bryant,8,8,2021-01-06,23-159,WAS,Away,PHI,L (-5),Yes,...,4,6,1,0,0,0,4,11,10.1,-14
21715,Thomas Bryant,9,9,2021-01-08,23-161,WAS,Away,BOS,L (-9),Yes,...,6,8,2,1,1,0,2,7,8.4,-12
21716,Thomas Bryant,10,10,2021-01-09,23-162,WAS,Home,MIA,L (-4),Yes,...,0,0,0,0,0,0,0,0,0.0,-4

In [54]:
df[df['minutes_played'].isna()]

,player,team_season_game,player_season_game,date_game,age,team_name,game_location,opponent_name,game_result,started_game,...,defensive_rebounds,total_rebounds,assists,steals,blocks,turn_overs,personal_fouls,points_scored,game_score,plus_minus
17865,Zach Collins,22,NaN,2021-02-06,23-079,POR,Away,NYK,L (-11),Not With Team,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17866,Zach Collins,30,NaN,2021-02-22,23-095,POR,Away,PHO,L (-32),Not With Team,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17867,Zach Collins,45,NaN,2021-03-26,23-127,POR,Away,ORL,W (+7),Not With Team,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17868,Zach Collins,56,NaN,2021-04-18,23-150,POR,Away,CHO,L (-8),Not With Team,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df.drop(df[df['minutes_played'].isna()].index, inplace=True)

In [56]:
df

,player,team_season_game,player_season_game,date_game,age,team_name,game_location,opponent_name,game_result,started_game,...,defensive_rebounds,total_rebounds,assists,steals,blocks,turn_overs,personal_fouls,points_scored,game_score,plus_minus
0,Solomon Hill,1,1,2020-12-23,29-280,ATL,Away,CHI,W (+20),No,...,3,3,0,0,1,3,2,0,-4.3,-8
1,Solomon Hill,2,2,2020-12-26,29-283,ATL,Away,MEM,W (+10),No,...,1,2,0,0,0,0,2,6,3.5,+3
2,Solomon Hill,3,3,2020-12-28,29-285,ATL,Home,DET,W (+8),No,...,2,2,0,1,1,1,3,12,8.1,+14
3,Solomon Hill,4,4,2020-12-30,29-287,ATL,Away,BRK,L (-4),No,...,1,2,0,0,0,1,3,9,4.8,-9
4,Solomon Hill,5,5,2021-01-01,29-289,ATL,Away,BRK,W (+18),No,...,4,4,1,1,1,0,1,6,3.7,+20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21712,Thomas Bryant,6,6,2021-01-01,23-154,WAS,Away,MIN,W (+21),Yes,...,5,7,2,0,0,2,1,18,17.4,+25
21713,Thomas Bryant,7,7,2021-01-03,23-156,WAS,Away,BRK,W (+1),Yes,...,12,14,2,1,0,1,4,21,21.0,-1
21714,Thomas Bryant,8,8,2021-01-06,23-159,WAS,Away,PHI,L (-5),Yes,...,4,6,1,0,0,0,4,11,10.1,-14
21715,Thomas Bryant,9,9,2021-01-08,23-161,WAS,Away,BOS,L (-9),Yes,...,6,8,2,1,1,0,2,7,8.4,-12
21716,Thomas Bryant,10,10,2021-01-09,23-162,WAS,Home,MIA,L (-4),Yes,...,0,0,0,0,0,0,0,0,0.0,-4

In [57]:
df.isna().any()

player                         False
team_season_game               False
player_season_game             False
date_game                      False
age                            False
team_name                      False
game_location                  False
opponent_name                  False
game_result                    False
started_game                   False
minutes_played                 False
field_goals_made               False
field_goals_attempts           False
field_goal_percentage          False
field_goals_three_made         False
field_goals_three_attempts     False
field_goal_three_percentage    False
free_throws_made               False
free_throw_attempts            False
free_throw_percentage          False
offensive_rebounds             False
defensive_rebounds             False
total_rebounds                 False
assists                        False
steals                         False
blocks                         False
turn_overs                     False
personal_fouls                 False
points_scored                  False
game_score                     False
plus_minus                      True
dtype: bool

In [58]:
df[df['plus_minus'].isna()]

,player,team_season_game,player_season_game,date_game,age,team_name,game_location,opponent_name,game_result,started_game,...,defensive_rebounds,total_rebounds,assists,steals,blocks,turn_overs,personal_fouls,points_scored,game_score,plus_minus
1331,Tacko Fall,31,7,2021-02-23,25-075,BOS,Away,DAL,L (-3),No,...,0,0,0,0,0,0,0,0,0.0,NaN
7611,Anthony Lamb,1,1,2021-03-11,23-050,HOU,Away,SAC,L (-20),No,...,1,1,0,0,0,0,2,3,0.1,NaN

In [59]:
df.drop(df[df['plus_minus'].isna()].index, inplace=True)

In [60]:
df

,player,team_season_game,player_season_game,date_game,age,team_name,game_location,opponent_name,game_result,started_game,...,defensive_rebounds,total_rebounds,assists,steals,blocks,turn_overs,personal_fouls,points_scored,game_score,plus_minus
0,Solomon Hill,1,1,2020-12-23,29-280,ATL,Away,CHI,W (+20),No,...,3,3,0,0,1,3,2,0,-4.3,-8
1,Solomon Hill,2,2,2020-12-26,29-283,ATL,Away,MEM,W (+10),No,...,1,2,0,0,0,0,2,6,3.5,+3
2,Solomon Hill,3,3,2020-12-28,29-285,ATL,Home,DET,W (+8),No,...,2,2,0,1,1,1,3,12,8.1,+14
3,Solomon Hill,4,4,2020-12-30,29-287,ATL,Away,BRK,L (-4),No,...,1,2,0,0,0,1,3,9,4.8,-9
4,Solomon Hill,5,5,2021-01-01,29-289,ATL,Away,BRK,W (+18),No,...,4,4,1,1,1,0,1,6,3.7,+20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21712,Thomas Bryant,6,6,2021-01-01,23-154,WAS,Away,MIN,W (+21),Yes,...,5,7,2,0,0,2,1,18,17.4,+25
21713,Thomas Bryant,7,7,2021-01-03,23-156,WAS,Away,BRK,W (+1),Yes,...,12,14,2,1,0,1,4,21,21.0,-1
21714,Thomas Bryant,8,8,2021-01-06,23-159,WAS,Away,PHI,L (-5),Yes,...,4,6,1,0,0,0,4,11,10.1,-14
21715,Thomas Bryant,9,9,2021-01-08,23-161,WAS,Away,BOS,L (-9),Yes,...,6,8,2,1,1,0,2,7,8.4,-12
21716,Thomas Bryant,10,10,2021-01-09,23-162,WAS,Home,MIA,L (-4),Yes,...,0,0,0,0,0,0,0,0,0.0,-4

In [61]:
df.isna().any()

player                         False
team_season_game               False
player_season_game             False
date_game                      False
age                            False
team_name                      False
game_location                  False
opponent_name                  False
game_result                    False
started_game                   False
minutes_played                 False
field_goals_made               False
field_goals_attempts           False
field_goal_percentage          False
field_goals_three_made         False
field_goals_three_attempts     False
field_goal_three_percentage    False
free_throws_made               False
free_throw_attempts            False
free_throw_percentage          False
offensive_rebounds             False
defensive_rebounds             False
total_rebounds                 False
assists                        False
steals                         False
blocks                         False
turn_overs                     False
personal_fouls                 False
points_scored                  False
game_score                     False
plus_minus                     False
dtype: bool

In [62]:
df.to_csv('../data/clean_2020_2021_nba_season_player_stats.csv', index=False)

Cleaned data with no NaN.